version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    command: postgres -c listen_addresses='*'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sreality_scraping:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    networks:
      - default
#    ports:
#      - 8761:8761
#    networks:
#      - default

volumes:
  db:
    driver: "local"

networks:
  default:
    driver: bridge