version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    command: postgres -c listen_addresses='*'
    user: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sreality_scraping:
    build:
      dockerfile: docker/scraping/Dockerfile
      context: .
    depends_on:
      - postgres
    networks:
      - my_network

  streamlit:
    build:
      dockerfile: docker/streamlit/Dockerfile
      context: .
    depends_on:
      - postgres
      - sreality_scraping
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  db:
    driver: "local"

networks:
  my_network: